root=,black
roottext=lightgray,black
border=gray,black
window=lightgray,black
shadow=black,black
title=lightgray,black
textbox=lightgray,black
entry=lightgray,black
label=lightgray,black
button=lightgray,black
actbutton=black,brown
compactbutton=lightgray,black
listbox=lightgray,black
actlistbox=black,brown
actsellistbox=lightgray,brown
checkbox=lightgray,black
actcheckbox=black,brown
emptyscale=gray,black
fullscale=black,brown
disabledentry=gray,black
helpline=gray,black
