root=,black
roottext=lightgray,black
border=gray,black
window=lightgray,black
shadow=black,black
title=lightgray,black
textbox=lightgray,black
entry=lightgray,black
label=lightgray,black
button=lightgray,black
actbutton=black,gray
compactbutton=lightgray,black
listbox=lightgray,black
actlistbox=black,gray
actsellistbox=lightgray,gray
checkbox=lightgray,black
actcheckbox=black,gray
emptyscale=gray,black
fullscale=black,gray
disabledentry=gray,black
helpline=gray,black
