root=,black
roottext=lightgray,black
border=gray,black
window=lightgray,black
shadow=black,black
title=brightmagenta,black
textbox=lightgray,black
entry=lightgray,black
label=lightgray,black
button=black,lightgray
actbutton=brightmagenta,gray
compactbutton=lightgray,black
listbox=lightgray,black
actlistbox=black,lightgray
actsellistbox=black,gray
checkbox=lightgray,black
actcheckbox=black,lightgray
emptyscale=gray,black
fullscale=black,lightgray
disabledentry=gray,black
helpline=gray,black
