# Variables, launch commands, and modifier aliases
#
# Wiki topics:
#   https://wiki.hypr.land/Configuring/Keywords/
#   https://wiki.hypr.land/Configuring/Binds/
#
# Syntax reminders:
#   $terminal = kitty
#   bind = $mainMod, RETURN, exec, $terminal

$mainMod = SUPER

$terminal = kitty
$fileManager = nautilus
$menu = ~/.local/bin/margine-launcher
$menuwalker = ~/.local/bin/margine-launcher-walker
$menusvc = ~/.local/bin/margine-launcher-service
$browser = firefox
