# Configurazione baseline per snap-pac in Margine v1

[root]
snapshot = True
cleanup_algorithm = number
important_packages = ["linux", "linux-lts", "amd-ucode", "intel-ucode", "systemd", "mkinitcpio", "cryptsetup", "sbctl", "limine", "snapper"]
important_commands = ["pacman -Syu"]
userdata = ["margine=yes", "scope=root", "source=pacman"]
